from imageprocessor.image_processor import ImageProcessor
from imageprocessor.image_processor import GCVProcessor
from imageprocessor.image_processor import AWSProcessor
# from imageprocessor.image_annotator import ImageAnnotator
